### ISSUE TITLE
Set up MkDocs with Material theme for Documentation Site

### ISSUE THREAD

**Issue by ohdearquant** [khive-ai/pydapter#36]
## Description

Create a comprehensive documentation site for pydapter using MkDocs with Material theme. This will improve discoverability, usability, and adoption of the library.

## Rationale

A well-structured documentation site is critical for library adoption. According to best practices from popular Python libraries, MkDocs with Material theme offers the best balance of features, aesthetics, and maintainability. Material for MkDocs is used by many successful projects including FastAPI, Typer CLI, and Pydantic.

The Material theme provides excellent search capabilities, responsive design, and customization options that will make pydapter's documentation more accessible and user-friendly.

## Tasks

- [ ] Install MkDocs and Material theme: `pip install mkdocs mkdocs-material mkdocstrings[python]`
- [ ] Create basic mkdocs.yml configuration file with the following settings:
  ```yml
  site_name: Pydapter
  site_description: A lightweight, type-safe adapter toolkit for Pydantic
  site_url: https://agenticsorg.github.io/pydapter/
  repo_name: agenticsorg/pydapter
  repo_url: https://github.com/agenticsorg/pydapter
  theme:
    name: material
    palette:
      primary: indigo
      accent: indigo
    features:
      - navigation.tabs
      - navigation.sections
      - search.suggest
      - search.highlight
  markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - admonition
    - pymdownx.tabbed
  plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            selection:
              inherited_members: true
            rendering:
              show_source: true
  ```
- [ ] Set up basic directory structure in docs/:
  ```
  docs/
  ├── index.md
  ├── getting-started/
  │   ├── installation.md
  │   ├── quickstart.md
  │   └── concepts.md
  ├── adapters/
  │   ├── core.md
  │   ├── file-formats/
  │   │   ├── json.md
  │   │   ├── csv.md
  │   │   └── toml.md
  │   └── databases/
  │       ├── postgres.md
  │       ├── mongodb.md
  │       ├── neo4j.md
  │       └── qdrant.md
  ├── api-reference/
  │   ├── core.md
  │   ├── adapters.md
  │   ├── async.md
  │   └── exceptions.md
  └── guides/
      ├── error-handling.md
      ├── async-usage.md
      └── custom-adapters.md
  ```
- [ ] Configure automatic API documentation generation with mkdocstrings in api-reference/ files
- [ ] Set up GitHub Actions workflow to build and deploy documentation to GitHub Pages:
  ```yml
  name: Deploy Documentation
  on:
    push:
      branches: [main]
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - run: pip install mkdocs-material mkdocstrings[python]
        - run: mkdocs gh-deploy --force
  ```
- [ ] Create initial landing page (index.md) with project overview
- [ ] Implement proper navigation structure in mkdocs.yml
- [ ] Set up syntax highlighting for code examples with proper Python formatting
- [ ] Configure search functionality
- [ ] Test local build with `mkdocs serve`
- [ ] Deploy initial version to GitHub Pages

## References

- Material for MkDocs documentation: https://squidfunk.github.io/mkdocs-material/
- Real Python article on Python project documentation: https://realpython.com/python-project-documentation-with-mkdocs/
- Example implementation in FastAPI docs: https://github.com/tiangolo/fastapi/tree/master/docs
- MkDocs configuration reference: https://www.mkdocs.org/user-guide/configuration/

## Expected Outcome

A basic but functional documentation site deployed to GitHub Pages with proper structure and navigation, ready for content to be added. The site should include:

1. A responsive layout that works well on mobile and desktop
2. Clear navigation structure matching the pydapter architecture
3. Search functionality
4. Syntax highlighting for code examples
5. GitHub repository link
6. Automated deployment process via GitHub Actions
